<?php declare(strict_types=1);

/* Copyright (c) 1998-2020 ILIAS open source, Extended GPL, see docs/LICENSE */

use ILIAS\DI\HTTPServices;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ServerRequestInterface;

require_once __DIR__ . '/../vendor/autoload.php';

/**
 * Class ilSkinChangerUIHookGUI
 * @author            Marvin Beym <mbeym@databay.de>
 * @ilCtrl_isCalledBy ilSkinChangerUIHookGUI: ilUIPluginRouterGUI
 */
class ilSkinChangerUIHookGUI extends ilUIHookPluginGUI
{
    protected ilCtrl $ctrl;
    protected ilObjUser $user;
    protected HTTPServices $http;
    /**
     * @var RequestInterface|ServerRequestInterface
     */
    protected $request;
    protected ?ilUserInterfaceHookPlugin $plugin;

    /**
     * ilRepositoryResubmissionUIHookGUI constructor.
     */
    public function __construct()
    {
        global $DIC;
        $this->ctrl = $DIC->ctrl();
        $this->user = $DIC->user();
        $this->http = $DIC->http();
        $this->request = $DIC->http()->request();
        $this->plugin = new ilSkinChangerPlugin();
    }

    /** @inheritDoc */
    public function checkGotoHook($a_target) : array
    {
        $pluginCommand = "skinChangeThroughLink";
        if ($a_target == $pluginCommand) {
            $this->ctrl->setTargetScript('ilias.php');
            $url = $this->ctrl->getLinkTargetByClass(
                [ilUIPluginRouterGUI::class, self::class],
                $pluginCommand
            );

            $query = parse_url($url, PHP_URL_QUERY);
            if (is_string($query)) {
                $parameters = [];
                parse_str($query, $parameters);
                if (!is_array($parameters) || !isset($parameters['baseClass'])) {
                    $url = ilUtil::appendUrlParameterString($url, 'baseClass=' . ilUIPluginRouterGUI::class);
                }
            }

            foreach ($this->request->getQueryParams() as $key => $queryParam) {
                if (in_array($key, ["target"])) {
                    continue;
                }
                $url = ilUtil::appendUrlParameterString($url, "{$key}={$queryParam}");
            }

            $this->ctrl->redirectToURL($url);
        }

        return parent::checkGotoHook($a_target); // TODO: Change the autogenerated stub
    }

    /**
     * @throws ilSystemStyleException
     * @return void
     */
    public function skinChangeThroughLink() : void
    {
        $skinId = $this->request->getQueryParams()["skin"];
        $styleId = "";

        if (!$skinId) {
            ilUtil::sendFailure($this->plugin->txt("skinParameterMissingInUrl"), true);
            $this->redirectToDashboard();
        }

        $foundSkin = false;
        foreach (ilStyleDefinition::getAllSkinStyles() as $skinStyle) {
            if ($skinId == $skinStyle["skin_id"]) {
                $foundSkin = true;
                $styleId = $skinStyle["style_id"];
                break;
            }
        }

        if (!$foundSkin) {
            ilUtil::sendFailure($this->plugin->txt("requestedSkinNotFound"), true);
            $this->redirectToDashboard();
        }

        if ($this->user->getPref("skinOverride") != $skinId) {
            $this->user->setPref("skinOverride", $skinId);
            $this->user->writePrefs();
            ilSkinChangerPlugin::setUserSkin($this->user, $skinId, $styleId);
        }

        $this->redirectToDashboard();
    }

    /**
     * Executes the requested command.
     * @return void
     */
    public function executeCommand()
    {
        if (!isset($this->request->getQueryParams()["cmd"])) {
            ilUtil::sendFailure($this->plugin->txt("cmdNotFound"), true);
            $this->redirectToDashboard();
        }

        $cmd = $this->request->getQueryParams()["cmd"];

        if ($this->user->isAnonymous()) {
            $additionalParameters = '';

            $target = ilUtil::stripSlashes((string) ($this->http->request()->getQueryParams()['target'] ?? ''));
            if (strlen($target) > 0) {
                $additionalParameters .= '&target=' . $target;
            }

            if (defined('CLIENT_ID')) {
                $additionalParameters .= '&client_id=' . CLIENT_ID;
            }
            $this->ctrl->redirectToURL('login.php?cmd=force_login' . $additionalParameters);
        }

        $this->performCommand($cmd);
    }

    /**
     * Calls the function for a received command
     * @param $cmd
     * @return void
     */
    public function performCommand($cmd)
    {
        switch (true) {
            case method_exists($this, $cmd):
                $this->{$cmd}();
                break;
        }
    }

    /** @inheritDoc */
    public function getHTML($a_comp, $a_part, $a_par = array()) : array
    {
        return parent::getHTML($a_comp, $a_part, $a_par);
    }

    /** @inheritDoc */
    public function modifyGUI($a_comp, $a_part, $a_par = array())
    {
    }

    /**
     * Redirects the user to the dashboard page
     * @return void
     */
    protected function redirectToDashboard()
    {
        $this->ctrl->redirectByClass(ilDashboardGUI::class, "show");
    }
}
